version: '3.8'
services:
  app:
    build: .
    depends_on:
      - mysql
    restart: always  
    ports: 
      - "8005:8080"
      
  
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=obo
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3306:3306"
    volumes:
      - ./obo.sql:/docker-entrypoint-initdb.d/init.sql
      - db_mysql:/var/lib/mysql
  
volumes:
  db_mysql: {}