version: '3.8'
services:
  app:
    build: .
    depends_on:
      - db
    ports: 
      - "8081:8080"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      
      
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: {}