version: '3.8'
services:
  demo-service:
    build: .
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/demo
      - PORT=3000
    depends_on:
      - mongodb
    ports: 
      - "8000:3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      
      
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'  
    volumes:
      - db_data:/data/db
volumes:
  db_data: {}